make-test refactoring
V4Fire/cli pull request #26
Opened 2023-07-17 06:16 UTC by misbiheyv

2023-07-19 13:26 UTC, gretzkiy commented on bin/cli.js
> +		'v4fire make-test page src/[path]/p-test',
Раз это конкретный пример, то мне кажется, не нужно добавлять плейсхолдеры типа `[path]`

2023-07-19 13:26 UTC, gretzkiy commented on src/templates/test/block/unit/main.ts
> +    component = await node.evaluateHandle((ctx) => ctx['component']['componentName']);
вроде бы в v4 есть хелпер, который возвращает компонент из ноды

2023-07-19 13:26 UTC, gretzkiy commented on src/templates/test/block/unit/main.ts
> +    node = await page.waitForSelector('#b-name-component');
лучше использовать локаторы

2023-07-19 13:26 UTC, gretzkiy commented on src/templates/test/page/project/main.ts
> +	});
что-то с отступами

2023-07-19 13:26 UTC, gretzkiy commented on src/templates/test/block/unit/main.ts
> +import type { RName } from 'src/components/b-name/b-name.ts';
А что это за тип такой? Мб тут должен быть импорт класса компонента как типа?

2023-07-24 11:45 UTC, kholstinin requested changes

2023-07-24 11:45 UTC, kholstinin commented on src/core/vfs.js
> +	findInDir(source, target) {
Может лучше просто взять glob?

2023-07-24 11:45 UTC, kholstinin commented on src/core/vfs.js
> +		return this.#copyDir(source, destination, options);
Мы не используем приватные методы

2023-07-24 11:45 UTC, kholstinin commented on src/core/vfs.js
> +	async #copyDir(source, destination, options = {}, pathStack = []) {
https://nodejs.org/docs/latest-v18.x/api/fs.html#fscpsrc-dest-options-callback

2023-07-24 11:45 UTC, kholstinin commented on src/controllers/make-test.js
> +		return content
Мне супер не нравится, что шаблоны это просто .js файлы и на них вызывается replace. Тут нужно использовать язык шаблонов, у нас для этого есть `.ss`, а вообще обычно используется handlebars. Хороший пример кодогенерации plop - https://plopjs.com/

2023-07-24 11:45 UTC, kholstinin commented on src/controllers/make-test.js
> +		return content
Наверное стоит написать шаблоны в .ss и собирать их с помощью .ss компилятора https://github.com/SnakeskinTpl/Snakeskin

2023-07-25 09:19 UTC, misbiheyv commented on src/controllers/make-test.js
> +		return content
Я создам новую задачу, внутри нее переведу шаблоны на формат `.hbs`. SS не пойдет, тк у нас шаблоны на ts, а ss в типы не умеет. Если ошибаюсь, то поправь меня

2023-07-25 09:27 UTC, misbiheyv commented on src/core/vfs.js
> +	async #copyDir(source, destination, options = {}, pathStack = []) {
это что?

2023-07-26 08:08 UTC, kholstinin commented on src/core/vfs.js
> +	async #copyDir(source, destination, options = {}, pathStack = []) {
Функция копирования директории есть в ноде
Используй ее, чем писать свою реализацию

2023-07-26 08:11 UTC, kholstinin commented on src/controllers/make-test.js
> +		return content
Давай тут же, не вижу смысла уносить в отдельную задачу, это совсем несложно

2023-08-02 10:19 UTC, kholstinin requested changes

2023-08-02 10:19 UTC, kholstinin commented on src/core/handlebars.js
> +  rl.once('line', (line) => {
Идею я понял, ты добавил информацию о том, как надо шаблонизировать файл в комментарий в самом верху шаблона, выглядит ок, но давай тогда функцию чтения первой строчки унесем в отдельную функцию в utils, `readFirstLine`

2023-08-02 10:19 UTC, kholstinin commented on src/core/handlebars.js
> +        {ext} = /^{{!.*((extension|ext)=(?<ext>[A-Za-z.]+?)[^A-Za-z.].*}}$)/g.exec(line).groups;
Регулярки конечно страшно выглядят, мб что нибудь проще сделать?
Там ведь одна строчка, можно туда json записать или более простой формат и распарсить его через split()

2023-08-04 13:24 UTC, misbiheyv commented on src/core/controller.js
> +			await this.copyTemplate(curSource, curDestinationFolder);
сделал resolveTemplate, render тоже кажется странным

2023-08-07 06:48 UTC, kholstinin commented on src/core/controller.js
> +				await this.copy(source, destination, options, [...pathStack, file]);
Здесь бы лучше через Promise.all()

2023-08-07 06:48 UTC, kholstinin commented on src/core/handlebars.js
> + * Reads a handlebars template and returns output file info
Тут более подробный коммент про формат, что в первой строке комментарий вот так выглядит и ты его парсишь в такую конструкцию

2023-08-07 06:48 UTC, kholstinin commented on src/templates/component/README.handlebars
> +{{/wrapInCodeBlock}}
Пустая строка

2023-08-07 06:48 UTC, kholstinin commented on src/core/handlebars.js
> +  opts.shift();
Выглядит нелепо)
Может лучше формат:
`{{! [[name]];ss }}`

`const [outputPath, extension] = line.trim().split(';');`

2023-08-07 06:48 UTC, kholstinin commented on yarn.lock
> +    handlebars: ^4.7.7
yarn.lock не перегенерил

2023-08-08 13:30 UTC, misbiheyv commented on src/core/handlebars.js
> +  opts.shift();
Тогда получится `['{{! [[name]]', 'ss }}']`

Можно так сделать еще:
`const [outputPath, extension] = line.split(/\s/).splice(1, line.split(/\s/).length - 2)`

2023-08-09 07:05 UTC, gretzkiy approved these changes

2023-08-09 07:05 UTC, gretzkiy commented on src/templates/app/src/base/b-hello-world/index.js
> +package("b-hello-world")
Почему двойные кавычки? Обычно же используем одинарные

2023-08-10 05:11 UTC, kholstinin commented on src/core/handlebars.js
> +  opts.shift();
Слишком многословно
Тогда можно
`line.slice(4, -3).split(';')`
Мы же знаем, сколько у нас символов занимает комментарий

2023-08-10 08:22 UTC, misbiheyv commented on src/core/handlebars.js
> +  opts.shift();
Я почему-то думал, что в js не работают отрицательные аргументы в этом методе 0_o

2023-08-10 08:56 UTC, kholstinin commented on src/core/handlebars.js
> + * Tt will be parsed into this: {name: 'index', ext: 'ts'}
It

2023-08-10 08:57 UTC, kholstinin approved these changes

2023-08-10 10:16 UTC, merged